-- MySQL Script generated by MySQL Workbench
-- Sat Jul 14 10:14:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vrpt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vrpt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vrpt` DEFAULT CHARACTER SET utf8 ;
USE `vrpt` ;

-- -----------------------------------------------------
-- Table `vrpt`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrpt`.`user` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `usertype` ENUM('student', 'teacher', 'admin') NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `nickname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vrpt`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrpt`.`teacher` (
  `teacherid` INT NOT NULL,
  `teachername` VARCHAR(45) NULL,
  UNIQUE INDEX `userid_UNIQUE` (`teacherid` ASC),
  CONSTRAINT `teacher_user`
    FOREIGN KEY (`teacherid`)
    REFERENCES `vrpt`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vrpt`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrpt`.`class` (
  `classid` VARCHAR(45) NOT NULL,
  `teacherid` INT NULL,
  PRIMARY KEY (`classid`),
  INDEX `class_teacher_idx` (`teacherid` ASC),
  CONSTRAINT `class_teacher`
    FOREIGN KEY (`teacherid`)
    REFERENCES `vrpt`.`teacher` (`teacherid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vrpt`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrpt`.`student` (
  `studentid` INT NOT NULL,
  `class` VARCHAR(45) NULL,
  `studentname` VARCHAR(45) NULL,
  UNIQUE INDEX `userid_UNIQUE` (`studentid` ASC),
  INDEX `student_class_idx` (`class` ASC),
  CONSTRAINT `student_user`
    FOREIGN KEY (`studentid`)
    REFERENCES `vrpt`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_class`
    FOREIGN KEY (`class`)
    REFERENCES `vrpt`.`class` (`classid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vrpt`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrpt`.`admin` (
  `adminid` INT NOT NULL,
  UNIQUE INDEX `adminid_UNIQUE` (`adminid` ASC),
  CONSTRAINT `admin_user`
    FOREIGN KEY (`adminid`)
    REFERENCES `vrpt`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vrpt`.`experiment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrpt`.`experiment` (
  `experimentid` INT NOT NULL,
  `experimentname` VARCHAR(45) NULL,
  `experimenturl` VARCHAR(45) NULL,
  PRIMARY KEY (`experimentid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vrpt`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrpt`.`report` (
  `reportid` INT NOT NULL,
  `studentid` INT NULL,
  `reporturl` VARCHAR(45) NULL,
  PRIMARY KEY (`reportid`),
  INDEX `report_student_idx` (`studentid` ASC),
  CONSTRAINT `report_student`
    FOREIGN KEY (`studentid`)
    REFERENCES `vrpt`.`student` (`studentid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `vrpt` ;

-- -----------------------------------------------------
-- Placeholder table for view `vrpt`.`studentView`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrpt`.`studentView` (`studentid` INT, `class` INT, `studentname` INT, `userid` INT, `username` INT, `usertype` INT, `password` INT, `phone` INT, `email` INT, `nickname` INT);

-- -----------------------------------------------------
-- Placeholder table for view `vrpt`.`teacherView`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrpt`.`teacherView` (`teacherid` INT, `teachername` INT, `userid` INT, `username` INT, `usertype` INT, `password` INT, `phone` INT, `email` INT, `nickname` INT);

-- -----------------------------------------------------
-- Placeholder table for view `vrpt`.`adminView`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrpt`.`adminView` (`adminid` INT, `userid` INT, `username` INT, `usertype` INT, `password` INT, `phone` INT, `email` INT, `nickname` INT);

-- -----------------------------------------------------
-- View `vrpt`.`studentView`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vrpt`.`studentView`;
USE `vrpt`;
CREATE  OR REPLACE VIEW `studentView` AS
SELECT * from `student` inner join `user` on `student`.studentid = `user`.userid;

-- -----------------------------------------------------
-- View `vrpt`.`teacherView`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vrpt`.`teacherView`;
USE `vrpt`;
CREATE  OR REPLACE VIEW `teacherView` AS
SELECT * from `teacher` inner join `user` on `teacher`.teacherid = `user`.userid;

-- -----------------------------------------------------
-- View `vrpt`.`adminView`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vrpt`.`adminView`;
USE `vrpt`;
CREATE  OR REPLACE VIEW `adminView` AS
SELECT * from `admin` inner join `user` on `admin`.adminid = `user`.userid;
CREATE USER 'vruser' IDENTIFIED BY '123456';

GRANT ALL ON `vrpt`.* TO 'vruser';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
